### PR TITLE
Update data.js to add entry for Sn (Tin)

### PR DESCRIPTION
**Pull request by kirtanprht**
Added an entry for Sn (Tin)

My own repo!

### CODE REVIEW

**Comment by ablakey** [comment]
Hey, I need to make that file multi-line.  Did you add Tin by re-running the script, or did you add it manually?

**Comment by kirtanprht** [comment]
I added it manually! Should I rerun the script?

**Comment by ablakey** [comment]
The script *should* pick up your repo if it's the most popular one by the name of "Tin".  But it's pretty inefficient. Because of GitHub throttling, it takes 13 mins.

Let me multi-line the data and then I'm going to ask you to re-raise this pull-request. It will be a lot more sane to review. =)

**Comment by ablakey** [comment]
There we go. Please re-apply your change. Sorry for the double effort, but it's much cleaner now. I wasn't expecting anyone to want to contribute :)

**Pull request closed without merging**
